workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never

stages:
  - backend-test
  - docker-deploy
  - frontend-build

backend:
  stage: backend-test
  image: php:8.2-fpm
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - backend/vendor/              
      - /root/.composer/cache 
  before_script:
    - apt-get update && apt-get install -y git curl zip unzip libpq-dev libzip-dev libonig-dev libsqlite3-dev sqlite3
    - docker-php-ext-install pdo pdo_mysql pdo_pgsql bcmath mbstring zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cd ./backend/ && composer install
  script:
    - |
      cat > .env <<'EOF'
      APP_NAME=NSSThermometerBackend
      APP_ENV=local
      APP_KEY=base64:zYgRkEuotrmHIkGQlAUY/VvTKOUSjjpWF7DLco5vRok=
      APP_DEBUG=true
      APP_URL=http://localhost
      LOG_CHANNEL=stack
      CACHE_DRIVER=file
      QUEUE_CONNECTION=sync
      DB_CONNECTION=sqlite
      DB_DATABASE=/builds/saxionnl/hbo-ict/2.3-devops/2024-2025/exam-regular/17/backend/database/database.sqlite
      EOF
    - php artisan migrate --force
    - mkdir -p ./tests/Unit && php artisan test --log-junit test-report.xml
  artifacts:
    paths:
      - ./backend/test-report.xml
    expire_in: 1 week

docker-register:
  stage: docker-deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE/backend:latest" -f backend/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE/backend:latest"

frontend:
  stage: frontend-build
  image: node:18-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/node_modules/   
      - /root/.npm 
  before_script:
    - pwd && cd ./frontend && npm install
  script:
    - npm run build
  artifacts:
    paths:
      - ./frontend/dist
    expire_in: 1 week
