services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: nss_thermometer
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  php-fpm:
    build:
      context: ./backend
    container_name: php-fpm
    volumes:
    - ./backend/app:/var/www/html/app:ro
    - ./backend/config:/var/www/html/config:ro
    - ./backend/routes:/var/www/html/routes:ro
    - ./backend/resources:/var/www/html/resources:ro
    - vendor_data:/var/www/html/vendor:ro
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: nss_thermometer
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  backend-nginx:
    image: nginx:stable-alpine
    container_name: backend-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php-fpm:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - internal
        - public

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      backend-nginx:
        condition: service_healthy
    networks:
      - internal
      - public

  seed:
    build:
      context: ./seed-application
    container_name: seeder
    environment:
      BACKEND_URL: http://backend-nginx
    depends_on:
      backend-nginx:
        condition: service_healthy
    networks:
      - internal

volumes:
  postgres-data:
  vendor_data:

networks:
  internal:
    internal: true
  public:
