version: '3.8'

services:
    # PostgreSQL Database
    db:
        image: postgres:13
        container_name: postgres
        environment:
            POSTGRES_DB: nss_thermometer
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U laravel"]
            interval: 10s
            timeout: 5s
            retries: 5

    # Laravel Backend (PHP-FPM)
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        volumes:
            - ./backend:/var/www/html
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: nss_thermometer
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/up"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - "8000:8000"
        command: php artisan serve --host=0.0.0.0 --port=8000

    # Seeder container
    seed:
        build:
            context: ./seed-application
            dockerfile: Dockerfile
        container_name: seeder
        depends_on:
            backend:
                condition: service_healthy
        environment:
            BACKEND_URL: http://backend:8000

volumes:
    postgres-data:
